### ISSUE TITLE
Bug No matching constructor overloading was found

### ISSUE THREAD

**Issue by Picus13** [Dan-Shields/League-OCR-HUD#10]
Hello, 
I have this return when i lauch the .after after config : 

```
Find status is 1.
Destroying find carrier.
Completing some receive creation work.
Error: No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.
    at Jimp.throwError (C:\Users\bonne\AppData\Local\Temp\caxa\applications\LeagueOCRHud\fz1nee6nmx\0\node_modules\@jimp\utils\dist\index.js:33:13)
    at new Jimp (C:\Users\bonne\AppData\Local\Temp\caxa\applications\LeagueOCRHud\fz1nee6nmx\0\node_modules\@jimp\core\dist\index.js:412:85)
    at NDI.<anonymous> (file:///C:/Users/bonne/AppData/Local/Temp/caxa/applications/LeagueOCRHud/fz1nee6nmx/0/src/index.js:156:13)
    at NDI.emit (node:events:527:28)
    at Worker.<anonymous> (file:///C:/Users/bonne/AppData/Local/Temp/caxa/applications/LeagueOCRHud/fz1nee6nmx/0/src/ndi.js:12:22)
    at Worker.emit (node:events:527:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  methodName: 'constructor'
}

```
Do you have any solution please ?

**Comment by Dan-Shields** [comment]
Which version of the program are you using, and are you using an pre-built executable or running from source?

**Comment by Picus13** [comment]
I have test with the 1.0.2 and 2.0.1 & and only with pre-built executable

edit : It's ok, i've reinstall node.js (LTS) and it's fine. Thanks
